#pragma once
#include "pch.h"
#include "WindowsTypes.h"
#include "Nidhogg.h"
#include "ProcessUtils.hpp"
#include "FileUtils.hpp"
#include "RegistryUtils.hpp"
#include "ModuleUtils.hpp"
#include "NidhoggDeviceControl.hpp"
